## YAML Template.
---
server:
  port: 8081
spring:
  retry:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    driverClassName: org.postgresql.Driver
    username: fangj
    password: passw0rd
  redis:
    host: localhost
    port: 6379
  security:
    enabled: false
  jpa:
    properties:
      hibernate:
        default_schema: hsbcdemo
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework: INFO
    org.springframework.retry: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info