## YAML Template.
---
spring:
  redis:
    host: master.fangjk-redis.7paiac.apse2.cache.amazonaws.com
    port: 6379
    password: zhu88jiezhu88jie
    ssl: true
  datasource:
    url: jdbc:postgresql://database-1.czcumcqkq9y5.ap-southeast-2.rds.amazonaws.com:5432/testdb
    driverClassName: org.postgresql.Driver
    username: postgres
    password: zhu88jie