## YAML Template.
---
server:
  port: 8081
spring:
  profiles:
    active: default,mixed
  cache:
    type: redis
  redis:
    host: 127.0.0.1
    port: 6379
  retry:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:postgresql://192.168.0.103:5432/testdb
    driverClassName: org.postgresql.Driver
    username: fangj
    password: passw0rd
  security:
    enabled: false
  jpa:
    properties:
      hibernate:
        default_schema: hsbcdemo
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.springframework.core.env: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health, metrics, info